name: Build
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Needed to write to GitHub draft release

env:
  RONIN_VERSION: ${{ github.ref_name }}

jobs:
  build-launcher:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup resource file version
        shell: bash
        run: |
          sed -i 's/DEV/${{ env.RONIN_VERSION }}/g' RoninLauncher/resources.rc
          FILEVERSION=$(echo ${{ env.RONIN_VERSION }} | tr '.' ',' | sed -E 's/-rc[0-9]+//' | tr -d '[:alpha:]')
          sed -i "s/0,0,0,1/${FILEVERSION}/g" RoninDLL/ns_version.h
      - name: Build
        run: |
          msbuild /p:Configuration=Release R2Ronin.sln
      - name: Upload launcher build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ronin-launcher
          path: |
            x64/Release/*.dll
            x64/Release/*.exe
            x64/Release/*.txt
      - name: Upload debug build artifact
        uses: actions/upload-artifact@v3
        with:
          name: launcher-debug-files
          path: |
            x64/Release/*.pdb

  upload-launcher-to-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-launcher
    runs-on: ubuntu-22.04
    steps:
      - name: Download compiled launcher
        uses: actions/download-artifact@v3
        with:
          name: ronin-launcher
          path: ronin-launcher
      - name: Download compiled launcher
        uses: actions/download-artifact@v3
        with:
          name: launcher-debug-files
          path: launcher-debug-files
      - name: Create zip to upload
        run: |
          zip --recurse-paths --quiet --junk-paths ronin-launcher.zip ronin-launcher/
          zip --recurse-paths --quiet --junk-paths launcher-debug-files.zip launcher-debug-files/
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        with:
          body: ":warning: These are development files! If you want to download Ronin, [go here instead](https://github.com/R2Ronin/Ronin/releases) :warning:"
          draft: false
          files: |
            ronin-launcher.zip
            launcher-debug-files.zip